# Generated by Django 5.1.6 on 2025-04-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_predictionresult_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionResult',
        ),
    ]
